apiVersion: v1
kind: Pod
metadata:
  name: kafka-0
  labels:
    app: kafka-0
spec:
  containers:
  - name: kafka-0
    image: confluentinc/cp-kafka:5.3.0
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
    ports:
      - containerPort: 9091
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: LISTENER_INTERNAL:PLAINTEXT
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: LISTENER_INTERNAL
    - name: KAFKA_ADVERTISED_LISTENERS
      value: LISTENER_INTERNAL://kafka-0:9091
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "false"
    - name: KAFKA_BROKER_ID
      value: "0"

---

apiVersion: v1
kind: Pod
metadata:
  name: kafka-1
  labels:
    app: kafka-1
spec:
  containers:
  - name: kafka-1
    image: confluentinc/cp-kafka:5.3.0
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
    ports:
      - containerPort: 9092
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: LISTENER_INTERNAL:PLAINTEXT
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: LISTENER_INTERNAL
    - name: KAFKA_ADVERTISED_LISTENERS
      value: LISTENER_INTERNAL://kafka-1:9092
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "false"
    - name: KAFKA_BROKER_ID
      value: "1"
    
---

apiVersion: v1
kind: Pod
metadata:
  name: kafka-2
  labels:
    app: kafka-2
spec:
  containers:
  - name: kafka-2
    image: confluentinc/cp-kafka:5.3.0
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
    ports:
      - containerPort: 9093
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: LISTENER_INTERNAL:PLAINTEXT
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: LISTENER_INTERNAL
    - name: KAFKA_ADVERTISED_LISTENERS
      value: LISTENER_INTERNAL://kafka-2:9093
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "false"
    - name: KAFKA_BROKER_ID
      value: "2"
    
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-0
spec:
  selector:
    app: kafka-0
  ports:
  - port: 9091
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  selector:
    app: kafka-1
  ports:
  - port: 9092
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  selector:
    app: kafka-2
  ports:
  - port: 9093
    protocol: TCP